FAIL
Kernel panic in run: PANIC at ../../lib/kernel/list.c:78 in list_next(): assertion `is_head (elem) || is_interior (elem)' failed.
Call stack: 0x800421387d 0x8004213af9 0x8004207ce5 0x800420a3fa 0x80042169b0 0x8004216a5d 0x8004210d80 0x8004216d78 0x8004219adf 0x8004216cb9 0x8004206636 0x8004206783 0x8004206120
Translation of call stack:
0x000000800421387d: debug_panic (lib/kernel/debug.c:32)
0x0000008004213af9: list_next (lib/kernel/list.c:79)
0x0000008004207ce5: remove_with_lock (threads/thread.c:730)
0x000000800420a3fa: lock_release (threads/synch.c:261)
0x00000080042169b0: release_console (lib/kernel/console.c:103)
0x0000008004216a5d: vprintf (lib/kernel/console.c:125)
0x0000008004210d80: printf (lib/stdio.c:80)
0x0000008004216d78: msg (tests/threads/tests.c:72)
0x0000008004219adf: test_priority_donate_chain (tests/threads/priority-donate-chain.c:76 (discriminator 4))
0x0000008004216cb9: run_test (tests/threads/tests.c:57)
0x0000008004206636: run_task (threads/init.c:252)
0x0000008004206783: run_actions (threads/init.c:297)
0x0000008004206120: main (threads/init.c:125)
